
package com.yodlee.handler;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddNumbersImpl", targetNamespace = "http://handler.yodlee.com/")
@HandlerChain(file = "AddNumbersImpl_handler.xml")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddNumbersImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws AddNumbersException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://handler.yodlee.com/", className = "com.yodlee.handler.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://handler.yodlee.com/", className = "com.yodlee.handler.AddNumbersResponse")
    @Action(input = "http://handler.yodlee.com/AddNumbersImpl/addNumbersRequest", output = "http://handler.yodlee.com/AddNumbersImpl/addNumbersResponse", fault = {
        @FaultAction(className = AddNumbersException_Exception.class, value = "http://handler.yodlee.com/AddNumbersImpl/addNumbers/Fault/AddNumbersException")
    })
    public int addNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws AddNumbersException_Exception
    ;

}
