
package com.yodlee.webservices.portfolio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EquityPortfolioImplService", targetNamespace = "http://portfolio.webservices.yodlee.com/", wsdlLocation = "http://localhost:8080/soap-web/portfolio?wsdl")
public class EquityPortfolioImplService
    extends Service
{

    private final static URL EQUITYPORTFOLIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EQUITYPORTFOLIOIMPLSERVICE_EXCEPTION;
    private final static QName EQUITYPORTFOLIOIMPLSERVICE_QNAME = new QName("http://portfolio.webservices.yodlee.com/", "EquityPortfolioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap-web/portfolio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EQUITYPORTFOLIOIMPLSERVICE_WSDL_LOCATION = url;
        EQUITYPORTFOLIOIMPLSERVICE_EXCEPTION = e;
    }

    public EquityPortfolioImplService() {
        super(__getWsdlLocation(), EQUITYPORTFOLIOIMPLSERVICE_QNAME);
    }

    public EquityPortfolioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EQUITYPORTFOLIOIMPLSERVICE_QNAME, features);
    }

    public EquityPortfolioImplService(URL wsdlLocation) {
        super(wsdlLocation, EQUITYPORTFOLIOIMPLSERVICE_QNAME);
    }

    public EquityPortfolioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EQUITYPORTFOLIOIMPLSERVICE_QNAME, features);
    }

    public EquityPortfolioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EquityPortfolioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EquityPortfolio
     */
    @WebEndpoint(name = "EquityPortfolioImplPort")
    public EquityPortfolio getEquityPortfolioImplPort() {
        return super.getPort(new QName("http://portfolio.webservices.yodlee.com/", "EquityPortfolioImplPort"), EquityPortfolio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquityPortfolio
     */
    @WebEndpoint(name = "EquityPortfolioImplPort")
    public EquityPortfolio getEquityPortfolioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://portfolio.webservices.yodlee.com/", "EquityPortfolioImplPort"), EquityPortfolio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EQUITYPORTFOLIOIMPLSERVICE_EXCEPTION!= null) {
            throw EQUITYPORTFOLIOIMPLSERVICE_EXCEPTION;
        }
        return EQUITYPORTFOLIOIMPLSERVICE_WSDL_LOCATION;
    }

}
